### ISSUE TITLE
IRR support

### ISSUE THREAD

**Issue by flynfish** [fintual-oss/fast-xirr#8]
Are you planning on supporting IRR?

**Comment by matias-martini** [comment]
Hi! Thanks for reaching out. Currently, we don’t have plans to support IRR in this gem, as we’re focused on keeping it lightweight and optimized for XIRR calculations specifically. However, forking this repository to extend it for IRR calculations would be fairly straightforward if you’d like to explore that. 

I may be able to look into it when time allows! But I can’t commit to a timeline just yet 😅
